### GET request hello
GET localhost:8080/response/hello

### GET request random
GET localhost:8080/response/random

### GET request message
GET localhost:8080/response/message

### GET request test
GET localhost:8080/response/test

### GET request map
GET localhost:8080/response/map

### GET request imapte (1.byte[] 방식)
GET localhost:8080/response/image/bytes/pikachu

### GET request imapte (2.WebConfig 방식)
GET localhost:8080/response/image/charmander.png

### GET request imapte (3. Resource 방식, 부분 동작, 캐시 비활성화, Http 1.0과 호환 가능(Pragma)
GET localhost:8080/response/image/resource/squirtle.png
Cache-Control: no-cache
Pragma: no-cache